"""add categories table

Revision ID: 16aad854975e
Revises: a9d3b3718a5b
Create Date: 2026-01-12 14:10:01.884201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16aad854975e'
down_revision = 'a9d3b3718a5b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('sku'))
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('old_price')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_active')
        batch_op.drop_column('image_url')
        batch_op.drop_column('stock')
        batch_op.drop_column('category')

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_product'))
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.create_index(batch_op.f('unique_user_product'), ['user_id', 'product_id'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('old_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_constraint(
            batch_op.f('products_ibfk_1'),
            type_='foreignkey'
        )

        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.create_index(batch_op.f('sku'), ['sku'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))




