"""Add role, user status reasons, admin activity logs

Revision ID: 83136b17de67
Revises: b5d37d07bade
Create Date: 2026-01-01 13:04:28.064991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83136b17de67'
down_revision = 'b5d37d07bade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.create_table('admin_activity_logs',
   # sa.Column('id', sa.Integer(), nullable=False),
   # sa.Column('admin_id', sa.Integer(), nullable=False),
    #sa.Column('action', sa.String(length=100), nullable=False),
    #a.Column('target_user_id', sa.Integer(), nullable=True),
    #sa.Column('ip_address', sa.String(length=45), nullable=True),
    #sa.Column('created_at', sa.DateTime(), nullable=False),
   # sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
   # sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    #sa.PrimaryKeyConstraint('id')
   # )


    op.create_table('user_status_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_status_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_status_reasons_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_status_reasons_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('login_activities', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

   # with op.batch_alter_table('wishlists', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('unique_user_product'))
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.create_index(batch_op.f('unique_user_product'), ['user_id', 'product_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('login_activities', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user_status_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_status_reasons_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_status_reasons_admin_id'))

    op.drop_table('user_status_reasons')
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_activity_logs_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_activity_logs_admin_id'))

    op.drop_table('admin_activity_logs')
    # ### end Alembic commands ###
