"""add review moderation fields

Revision ID: b2c254ba4467
Revises: 
Create Date: 2025-12-25 22:43:33.937879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c254ba4467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_reported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('report_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_product'))
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('unique_user_product'), ['user_id', 'product_id'], unique=True)

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_column('report_reason')
        batch_op.drop_column('is_reported')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
