"""add login activity table

Revision ID: b5d37d07bade
Revises: b2c254ba4467
Create Date: 2025-12-31 12:12:34.139879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5d37d07bade'
down_revision = 'b2c254ba4467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('login_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_activities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_constraint(batch_op.f('product_reviews_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('product_reviews_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_product'))
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('wishlists_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('wishlists_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.create_index(batch_op.f('unique_user_product'), ['user_id', 'product_id'], unique=True)

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_reviews_ibfk_2'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('product_reviews_ibfk_1'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('login_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_activities_created_at'))

    op.drop_table('login_activities')
    # ### end Alembic commands ###
